## [1] 데이터 준비
---

In [1]:
from sklearn.datasets import fetch_20newsgroups
newsData = fetch_20newsgroups(subset = 'all', remove=('headers', 'footer'))

In [2]:
newsData.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [3]:
newsData20 = newsData['data']
type(newsData20)

list

In [4]:
len(newsData20)

18846

In [8]:
print(type(newsData20[0]))
print(newsData20[0])

<class 'str'>


I am sure some bashers of Pens fans are pretty confused about the lack
of any kind of posts about the recent Pens massacre of the Devils. Actually,
I am  bit puzzled too and a bit relieved. However, I am going to put an end
to non-PIttsburghers' relief with a bit of praise for the Pens. Man, they
are killing those Devils worse than I thought. Jagr just showed you why
he is much better than his regular season stats. He is also a lot
fo fun to watch in the playoffs. Bowman should let JAgr have a lot of
fun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final
regular season game.          PENS RULE!!!




In [6]:
print(newsData20[3])


In article <1993Apr19.034517.12820@julian.uwo.ca>, wlsmith@valve.heart.rri.uwo.ca (Wayne Smith) writes:
> In article <RICHK.93Apr15075248@gozer.grebyn.com> richk@grebyn.com (Richard Krehbiel) writes:
> >>     Can anyone explain in fairly simple terms why, if I get OS/2, I might 
> >>   need an SCSI controler rather than an IDE.  Will performance suffer that
> >>   much?  For a 200MB or so drive?  If I don't have a tape drive or CD-ROM?
> >>   Any help would be appreciated.
> 
> >So, when you've got multi-tasking, you want to increase performance by
> >increasing the amount of overlapping you do.
> >
> >One way is with DMA or bus mastering.  Either of these make it
> >possible for I/O devices to move their data into and out of memory
> >without interrupting the CPU.  The alternative is for the CPU to move
> >the data.  There are several SCSI interface cards that allow DMA and
> >bus mastering.
>  ^^^^^^^^^^^^
> How do you do bus-mastering on the ISA bus?
> 
> >IDE, however, is defined 

In [9]:
# 타겟 데이터 확인
target = newsData['target']
type(target)

numpy.ndarray

In [10]:
print(f'target => {len(newsData["target_names"])}개')
for name in newsData['target_names']:
    print(name)
print(f'target => {target}')

target => 20개
alt.atheism
comp.graphics
comp.os.ms-windows.misc
comp.sys.ibm.pc.hardware
comp.sys.mac.hardware
comp.windows.x
misc.forsale
rec.autos
rec.motorcycles
rec.sport.baseball
rec.sport.hockey
sci.crypt
sci.electronics
sci.med
sci.space
soc.religion.christian
talk.politics.guns
talk.politics.mideast
talk.politics.misc
talk.religion.misc
target => [10  3 17 ...  3  1  7]


# @@@ 텍스트 전처리(Text preprocessing) @@@

## [2] 데이터 전처리
---
- (1) 수집 데이터 기반 단어사전 생성
- (2) 텍스트 데이터 -> 수치 데이터 변환
- (3) 데이터 길이 결정
- (4) 이진 정수화 변환

[ 필요한 처리 ]
---
- 불필요한 문자 혹은 숫자 그리고 특수기호들을 제거 -> 정규식
- 불용어 제거
- 대 소문자 통일화
- 표제어 추출 (Lemmatization)
- 어간 추출 (Stemming)
- HTML 태그 제거 등..

### [2-1] 단어사전 생성
---

## 1) 토큰화

In [11]:
# 모듈
# nltk.download('all')
from nltk.tokenize import sent_tokenize, word_tokenize

# 해당 데이터 셋에서 각 문장들을 하나의 리스트에 담기 (문장 합치기)
textAll = []
for n in range(len(newsData20)):
    textAll.append(newsData20[n])

In [12]:
# 해당 text에서 문장을 하나씩 추출
for num in range(len(textAll)):    
    total_token = []

    # 문장 단위로 추출해서 토큰화 (리스트에 담아줌)
    sentResult = sent_tokenize(textAll[num])
    
    # 리스트에서 문장을 꺼내 단어 단위로 토큰화
    for snt in sentResult:
        # print(f' snt => {snt}')
        wordResult = word_tokenize(snt)
        total_token.append(wordResult)
        # print(f' snt => {sentResult}\n')

In [13]:
total_token

[['After',
  'a',
  'tip',
  'from',
  'Gary',
  'Crum',
  '(',
  'crum',
  '@',
  'fcom.cc.utah.edu',
  ')',
  'I',
  'got',
  'on',
  'the',
  'Phone',
  'with',
  '``',
  'Pontiac',
  'Systems',
  "''",
  'or',
  '``',
  'Pontaic',
  'Customer',
  'Service',
  "''",
  'or',
  'whatever',
  ',',
  'and',
  'inquired',
  'about',
  'a',
  'rumoured',
  'Production',
  'Hold',
  'on',
  'the',
  'Formula',
  'Firebird',
  'and',
  'Trans',
  'Am',
  '.'],
 ['BTW',
  ',',
  'Talking',
  'with',
  'the',
  'dealer',
  'I',
  'bought',
  'the',
  'car',
  'from',
  'got',
  'me',
  'nowhere',
  '.'],
 ['After',
  'being',
  'routed',
  'to',
  'a',
  '``',
  'Firebird',
  'Specialist',
  "''",
  ',',
  'I',
  'was',
  'able',
  'to',
  'confirm',
  'that',
  'this',
  'is',
  'in',
  'fact',
  'the',
  'case',
  '.'],
 ['At',
  'first',
  ',',
  'there',
  'was',
  'some',
  'problem',
  'with',
  'the',
  '3:23',
  'performance',
  'axle',
  'ratio',
  '.'],
 ['She',
  'would',
  "n't",


---

In [14]:
# 품사 태깅(part-of-speech tagging)
# : 토큰화 과정에서 각 단어가 어떤 품사로 쓰였는지를 구분하는 것
# ex) 부사 '못'은 동작동사를 수식할 수 없는 등의 문법적인 요소가 있는 것도 있으므로

In [15]:
text = "I am actively looking for Ph.D. students. and you are a Ph.D. student."
tokenized_sentence = word_tokenize(text)
print(type(tokenized_sentence))
print(type(total_token))

<class 'list'>
<class 'list'>


In [16]:
# NLTK 영어 토큰화 실습
from nltk.tokenize import word_tokenize

# NLTK에서는 Penn Treebank POS Tags라는 기준을 사용하여 품사를 태깅
from nltk.tag import pos_tag

print('품사 태깅 :',pos_tag(total_token[0]))

품사 태깅 : [('After', 'IN'), ('a', 'DT'), ('tip', 'NN'), ('from', 'IN'), ('Gary', 'NNP'), ('Crum', 'NNP'), ('(', '('), ('crum', 'JJ'), ('@', 'NNP'), ('fcom.cc.utah.edu', 'NN'), (')', ')'), ('I', 'PRP'), ('got', 'VBD'), ('on', 'IN'), ('the', 'DT'), ('Phone', 'NN'), ('with', 'IN'), ('``', '``'), ('Pontiac', 'JJ'), ('Systems', 'NNPS'), ("''", "''"), ('or', 'CC'), ('``', '``'), ('Pontaic', 'NNP'), ('Customer', 'NNP'), ('Service', 'NNP'), ("''", "''"), ('or', 'CC'), ('whatever', 'VB'), (',', ','), ('and', 'CC'), ('inquired', 'VBD'), ('about', 'IN'), ('a', 'DT'), ('rumoured', 'JJ'), ('Production', 'NNP'), ('Hold', 'NNP'), ('on', 'IN'), ('the', 'DT'), ('Formula', 'NNP'), ('Firebird', 'NNP'), ('and', 'CC'), ('Trans', 'NNP'), ('Am', 'NNP'), ('.', '.')]


In [36]:
# 1) 불필요한 문자 혹은 숫자 그리고 특수기호들을 제거 -> 정규식
# 어포스트로피 관련
from tensorflow.keras.preprocessing.text import text_to_word_sequence
# - 케라스에서 제공하는 [ text_to_word_sequence ]의 경우,
# i) 모든 알파벳을 소문자로 바꿈
# ii) 마침표나 컴마, 느낌표 등의 구두점을 제거
# iii) don't나 jone's와 같은 경우 아포스트로피는 보존

from nltk.tokenize import sent_tokenize
print('문장 토큰화1 :',sent_tokenize(newsData20[0]))
# - NLTK에서는 영어 문장의 토큰화를 수행하는 sent_tokenize를 지원

문장 토큰화1 : ['\n\nI am sure some bashers of Pens fans are pretty confused about the lack\nof any kind of posts about the recent Pens massacre of the Devils.', 'Actually,\nI am  bit puzzled too and a bit relieved.', "However, I am going to put an end\nto non-PIttsburghers' relief with a bit of praise for the Pens.", 'Man, they\nare killing those Devils worse than I thought.', 'Jagr just showed you why\nhe is much better than his regular season stats.', 'He is also a lot\nfo fun to watch in the playoffs.', 'Bowman should let JAgr have a lot of\nfun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway.', 'I was very disappointed not to see the Islanders lose the final\nregular season game.', 'PENS RULE!!', '!']


---

## 2) 정제

In [37]:
# 정제 작업에서 제거해야하는 노이즈 데이터(noise data)
# - 자연어가 아니면서 아무 의미도 갖지 않는 글자들(특수 문자 등)을 의미
# - 덧붙여, 분석하고자 하는 목적에 맞지 않는 불필요 단어들을 노이즈 데이터

# 2-1) 불용어 제거
# 불용어(stopword) :  유의미한 단어 토큰만을 선별하기 위해서는 큰 의미가 없는 단어 토큰
# - 큰 의미가 없다 : 라는 것은 자주 등장하지만 분석을 하는 것에 있어서는 큰 도움이 되지 않는 단어들


In [40]:
# [ 영어 ]
# 불용어는 개발자가 직접 정의할 수도 있음
# (1) NLTK에서 불용어 확인하기(179개)
# (2) NLTK를 통해서 불용어 제거하기

In [41]:
# 불용어 확인
from nltk.corpus import stopwords
stop_words_list = stopwords.words('english')
print('불용어 개수 :', len(stop_words_list))
print('불용어 10개 출력 :',stop_words_list[:10])

불용어 개수 : 179
불용어 10개 출력 : ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]


In [39]:
# 불용어 제거
example = "Family is not an important thing. It's everything."
stop_words = set(stopwords.words('english')) 

word_tokens = word_tokenize(example)   # 단어 토큰화

result = []
for word in word_tokens: 
    if word not in stop_words: 
        result.append(word) 

print('불용어 제거 전 :',word_tokens) 
print('불용어 제거 후 :',result)

불용어 제거 전 : ['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
불용어 제거 후 : ['Family', 'important', 'thing', '.', 'It', "'s", 'everything', '.']


In [ ]:
# [ 한글 ] ------ 주제에 맞는 것들을 담아서
# 간단하게 토큰화 후에 조사, 접속사 등을 제거하는 방법
# - 조사나 접속사와 같은 단어들뿐만 아니라
# - 명사, 형용사와 같은 단어들 중에서 불용어로서 제거하고 싶은 단어들이 생기기도
#  => 결국에는 사용자가 직접 불용어 사전을 만들게 되는 경우가 많음

# 직접 불용어를 정의해보고,
# 주어진 문장으로부터 사용자가 정의한 불용어 사전으로부터 불용어를 제거

In [22]:
# 불용어 제거 
from konlpy.tag import Okt
okt = Okt()

example = "고기를 아무렇게나 구우려고 하면 안 돼. 고기라고 다 같은 게 아니거든. 예컨대 삼겹살을 구울 때는 중요한 게 있지."
stop_words = "를 아무렇게나 구 우려 고 안 돼 같은 게 구울 때 는"

stop_words = set(stop_words.split(' '))
word_tokens = okt.morphs(example)

result = [word for word in word_tokens if not word in stop_words]

print('불용어 제거 전 :',word_tokens, sep='\n')
print()
print('불용어 제거 후 :',result, sep='\n')

불용어 제거 전 :
['고기', '를', '아무렇게나', '구', '우려', '고', '하면', '안', '돼', '.', '고기', '라고', '다', '같은', '게', '아니거든', '.', '예컨대', '삼겹살', '을', '구울', '때', '는', '중요한', '게', '있지', '.']

불용어 제거 후 :
['고기', '하면', '.', '고기', '라고', '다', '아니거든', '.', '예컨대', '삼겹살', '을', '중요한', '있지', '.']


In [ ]:
# 2-2) 등장 빈도가 적은 단어 제거
# - 너무 적게 등장해서 자연어 처리에 도움이 되지 않는 단어들이 존재
# - 직관적으로 분류에 거의 도움이 되지 않을 것임

In [ ]:
# 2-3) 길이가 짧은 단어 제거 (아래의 예시 참고)
# - 영어권 언어에서는 길이가 짧은 단어를 삭제하는 것만으로도
# - 어느정도 자연어 처리에서 크게 의미가 없는 단어들을 제거하는 효과를 볼 수 있다고 알려져 있음
# - 길이를 조건으로 텍스트를 삭제하면서 단어가 아닌 구두점들까지도 한꺼번에 제거하는 효과도 있음
# - 덧붙여, 길이1 : 관사 'a'나 주어 'I'도 함께 제거
# - 길이2 : in, by 등 전치사도 제거
# - 길이3 : car, dog같은 명사 단어가 지워질 수 있으니 nope! (고민필요)

# - but, 한국어에서는 길이가 짧은 단어라고 삭제하는 이런 방법이 크게 유효하지 않을 수 있음

In [ ]:
# 2-4) 정규 표현식 (제거 방법)
# 얻어낸 코퍼스에서 노이즈 데이터의 특징을 잡아낼 수 있다면,
# 정규 표현식을 통해서 이를 제거할 수 있는 경우가 많음
# 정규 표현식은 이러한 코퍼스 내에 계속해서 등장하는 글자들을 규칙에 기반,
# 한 번에 제거하는 방식으로서 매우 유용

In [42]:
import re
text = "I was wondering if anyone out there could enlighten me on this car."

# 길이가 1~2인 단어들을 정규 표현식을 이용하여 삭제
shortword = re.compile(r'\W*\b\w{1,2}\b')
print(shortword.sub('', text))

 was wondering anyone out there could enlighten this car.


---

## 3) 정규화

In [138]:
# 3-1) 어간 추출 및 표제어 추출
# 목적 : 하나의 단어로 일반화시킬 수 있다면, 하나의 단어로 일반화 -> 문서 내의 단어 수를 줄이자
# -> 표기가 다르지만, 뜻은 같은 것들을 통합하는 과정
# -> 어간 추출(stemming)과 표제어 추출(lemmatizaiton)

# 이러한 방법들은 단어의 빈도수를 기반으로 문제를 풀고자 하는,
# 뒤에서 학습하게 될 BoW(Bag of Words) 표현을 사용하는 자연어 처리 문제에서 주로 사용

# 자연어 처리에서 전처리,
# 더 정확히는 정규화의 지향점은 언제나 갖고 있는 코퍼스로부터 복잡성을 줄이는 일임!!

# 이미 알려진 알고리즘을 사용할 때는,
# 사용하고자 하는 코퍼스에 스태머를 적용해보고 어떤 스태머가 해당 코퍼스에 적합한지를 판단한 후에 사용해야 함

In [ ]:
# [ 표제어 추출 ]
# 표제어(Lemma) : 한글로는 '표제어' 또는 '기본 사전형 단어' 정도의 의미
# => 표제어 추출은 단어들로부터 표제어를 찾아가는 과정

# NLTK에서는 표제어 추출을 위한 도구인 WordNetLemmatizer를 지원 (아래 예시)
# - 표제어 추출기(lemmatizer)가 본래 단어의 품사 정보를 알아야만 정확한 결과를 얻을 수 있음
# - WordNetLemmatizer는 입력으로 단어가 동사 품사라는 사실을 알려줄 수 있습니다.
#  -> 즉, dies와 watched, has가 문장에서 동사로 쓰였다는 것을 알려준다면
#  -> 표제어 추출기는 품사의 정보를 보존하면서 정확한 Lemma를 출력하게 됩니다.
# ex) 아래 예시

In [24]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

print('표제어 추출 전 :',total_token[0])
print()
print('표제어 추출 후 :',[lemmatizer.lemmatize(word) for word in total_token[0]])

표제어 추출 전 : ['After', 'a', 'tip', 'from', 'Gary', 'Crum', '(', 'crum', '@', 'fcom.cc.utah.edu', ')', 'I', 'got', 'on', 'the', 'Phone', 'with', '``', 'Pontiac', 'Systems', "''", 'or', '``', 'Pontaic', 'Customer', 'Service', "''", 'or', 'whatever', ',', 'and', 'inquired', 'about', 'a', 'rumoured', 'Production', 'Hold', 'on', 'the', 'Formula', 'Firebird', 'and', 'Trans', 'Am', '.']

표제어 추출 후 : ['After', 'a', 'tip', 'from', 'Gary', 'Crum', '(', 'crum', '@', 'fcom.cc.utah.edu', ')', 'I', 'got', 'on', 'the', 'Phone', 'with', '``', 'Pontiac', 'Systems', "''", 'or', '``', 'Pontaic', 'Customer', 'Service', "''", 'or', 'whatever', ',', 'and', 'inquired', 'about', 'a', 'rumoured', 'Production', 'Hold', 'on', 'the', 'Formula', 'Firebird', 'and', 'Trans', 'Am', '.']


In [25]:
# 단어의 품사가 무엇인지 알려줌
print(lemmatizer.lemmatize('dies', 'v'))
print(lemmatizer.lemmatize('watched', 'v'))

die
watch


In [26]:
# [ 어간 추출 ]
# 간 추출을 수행한 결과는 품사 정보가 보존되지 않습니다.
# - 더 정확히는 어간 추출을 한 결과는 '사전에 존재하지 않는 단어'일 경우가 많습니다.
# - 정해진 규칙만 보고 단어의 어미를 자르는 어림짐작의 작업

# 어간 추출 알고리즘 중 하나인 '포터 알고리즘(Porter Algorithm)'
# - ex) 아래 예시

# 어간 추출 속도는 표제어 추출보다 일반적으로 빠른데,
# - 포터 어간 추출기는 정밀하게 설계되어 정확도가 높으므로
# - 영어 자연어 처리에서 어간 추출을 하고자 한다면 가장 준수한 선택

In [28]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

stemmer = PorterStemmer()

sentence = "This was not the map we found in Billy Bones's chest, but an accurate copy, complete in all things--names and heights and soundings--with the single exception of the red crosses and the written notes."
tokenized_sentence = word_tokenize(sentence)

print('어간 추출 전 :', tokenized_sentence)
print()
print('어간 추출 후 :',[stemmer.stem(word) for word in tokenized_sentence])

어간 추출 전 : ['This', 'was', 'not', 'the', 'map', 'we', 'found', 'in', 'Billy', 'Bones', "'s", 'chest', ',', 'but', 'an', 'accurate', 'copy', ',', 'complete', 'in', 'all', 'things', '--', 'names', 'and', 'heights', 'and', 'soundings', '--', 'with', 'the', 'single', 'exception', 'of', 'the', 'red', 'crosses', 'and', 'the', 'written', 'notes', '.']

어간 추출 후 : ['thi', 'wa', 'not', 'the', 'map', 'we', 'found', 'in', 'billi', 'bone', "'s", 'chest', ',', 'but', 'an', 'accur', 'copi', ',', 'complet', 'in', 'all', 'thing', '--', 'name', 'and', 'height', 'and', 'sound', '--', 'with', 'the', 'singl', 'except', 'of', 'the', 'red', 'cross', 'and', 'the', 'written', 'note', '.']


In [29]:
# 3-2) 대, 소문자 통합
# - 물론 대문자와 소문자를 무작정 통합해서는 안됨
# - 대문자와 소문자가 구분되어야 하는 경우도 있음
# - 결국에는 예외 사항을 크게 고려하지 않고,
#  => 모든 코퍼스를 소문자로 바꾸는 것이 종종 더 실용적인 해결책이 되기도 함 (v)

---

## 4) 정수 인코딩(Integer Encoding)

In [66]:
# 컴퓨터는 텍스트보다 숫자를 더 잘 처리
# 자연어 처리 과정에서 텍스트 -> 숫자로 바꾸는 기법의 첫 단계 => 각 단어를 정수에 매핑(mapping) 시키기
# - 왜 이러한 작업이 필요한 지에 대해서는 뒤에서 원-핫 인코딩 실습이나, 워드 임베딩 챕터 등에서 알아보기로
# 단어를 빈도수 순으로 정렬한 단어 집합(vocabulary)을 만들고, 빈도수가 높은 순서대로 차례로 낮은 숫자부터 정수를 부여하는 방법

---

In [67]:
# 1) dictionary 사용하기

from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# raw_text = "A barber is a person. a barber is good person. a barber is huge person. \
# he Knew A Secret! The Secret He Kept is huge secret. Huge secret. \
# His barber kept his word. a barber kept his word. His barber kept his secret. \
# But keeping and keeping such a huge secret to himself was driving the barber crazy. \
# the barber went up a huge mountain."

raw_text = '''A barber is a person. a barber is good person. a barber is huge person. 
he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. 
a barber kept his word. His barber kept his secret. 
But keeping and keeping such a huge secret to himself was driving the barber crazy. 
the barber went up a huge mountain.'''

In [68]:
# 문장 토큰화
sentences = sent_tokenize(raw_text)
print(sentences)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [69]:
# 기존의 텍스트 데이터가 문장 단위로 토큰화 된 것을 확인
# -> 이제 정제 작업과 정규화 작업을 병행하며, 단어 토큰화를 수행

#### *** 문장 토큰화 -> 정제 & 정규화 -> 단어 토큰화

In [70]:
# - 단어들을 소문자화하여 단어의 개수를 통일
# - 불용어와 단어 길이가 2이하인 경우에 대해서 단어를 일부 제외

# 텍스트를 수치화하는 단계라는 것은 본격적으로 자연어 처리 작업에 들어간다는 의미!!
# => 단어가 텍스트일 때만 할 수 있는 최대한의 전처리를 끝내놓아야 합니다.

# 등장 빈도가 낮은 단어는 자연어 처리에서 의미를 가지지 않을 가능성이 높기 때문에
# ex) 빈도수가 1인 단어들은 전부 제외
# word_to_index에는 빈도수가 높은 상위 5개의 단어만 저장됨
# word_to_index를 사용 -> 단어 토큰화가 된 상태로 저장된 sentences에 있는 각 단어를 정수로 바꾸는 작업

#------------------------------------------------------------------------------------------------------------------------
# 예를 들어 sentences에서 첫번째 문장은 ['barber', 'person']이었는데, 이 문장에 대해서는 [1, 5]로 인코딩합니다.
# 그런데 두번째 문장인 ['barber', 'good', 'person']에는 더 이상 word_to_index에는 존재하지 않는 단어인 'good'이라는 단어가 있습니다.
# -> 이처럼 단어 집합에 존재하지 않는 단어들이 생기는 상황을 Out-Of-Vocabulary(단어 집합에 없는 단어) 문제라고 합니다.
# -> 약자로 'OOV 문제'라고도 합니다. word_to_index에 'OOV'란 단어를 새롭게 추가하고, 단어 집합에 없는 단어들은 'OOV'의 인덱스로 인코딩하겠습니다.
# -> word_to_index를 사용하여 sentences의 모든 단어들을 맵핑되는 정수로 인코딩
#------------------------------------------------------------------------------------------------------------------------

# => 이런걸 해주는 keras 모듈이 있으니 상황에 따라서 그걸 써도 편리 (해당 설명은 파이썬)
# => 즉, Counter, FreqDist, enumerate를 사용하거나, 케라스 토크나이저를 사용하는 것을 권장

In [71]:
# 2) Counter 사용하기

from collections import Counter

preprocessed_sentences = [['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]
print(preprocessed_sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [72]:
# 현재 sentences는 단어 토큰화가 된 결과가 저장되어져 있음
# - 단어 집합(vocabulary)을 만들기 위해서 sentences에서 문장의 경계인 [, ]를 제거하고 단어들을 하나의 리스트로 만듦

# words = np.hstack(preprocessed_sentences)으로도 수행 가능.
all_words_list = sum(preprocessed_sentences, [])
print(all_words_list)

['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']


In [73]:
# 이를 파이썬의 Counter()의 입력으로 사용하면 '중복을 제거'하고 단어의 빈도수를 기록
# 파이썬의 Counter 모듈을 이용하여 단어의 빈도수 카운트
vocab = Counter(all_words_list)
print(vocab)

Counter({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})


In [74]:
# 단어를 키(key)로, 단어에 대한 빈도수가 값(value)으로 저장되어져 있습니다. vocab에 단어를 입력하면 빈도수를 리턴
print(vocab["barber"]) # 'barber'라는 단어의 빈도수 출력

8


In [75]:
# barber란 단어가 총 8번 등장하였습니다. most_common()는 상위 빈도수를 가진 주어진 수의 단어만을 리턴합니다.
# -> 이를 사용하여 등장 빈도수가 높은 단어들을 원하는 개수만큼만 얻을 수 있음
# -> 등장 빈도수 상위 5개의 단어만 단어 집합으로 저장

vocab_size = 5
vocab = vocab.most_common(vocab_size) # 등장 빈도수가 높은 상위 5개의 단어만 저장
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [76]:
# 높은 빈도수를 가진 단어일수록 낮은 정수 인덱스를 부여

word_to_index = {}
i = 0
for (word, frequency) in vocab :
    i = i + 1
    word_to_index[word] = i

print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


---

In [77]:
# 3) NLTK의 FreqDist 사용하기

# NLTK에서는 빈도수 계산 도구인 FreqDist()를 지원함
# 위에서 사용한 Counter()랑 같은 방법으로 사용할 수 있음

In [78]:
from nltk import FreqDist
import numpy as np

# np.hstack으로 문장 구분을 제거
vocab = FreqDist(np.hstack(preprocessed_sentences))

In [79]:
# 단어를 키(key)로, 단어에 대한 빈도수가 값(value)으로 저장되어져 있음
# -> vocab에 단어를 입력하면 빈도수를 리턴

print(vocab["barber"]) # 'barber'라는 단어의 빈도수 출력

8


In [80]:
# most_common()는 상위 빈도수를 가진 주어진 수의 단어만을 리턴
# 이를 사용하여 등장 빈도수가 높은 단어들을 원하는 개수만큼만 얻을 수 있음
# 등장 빈도수 상위 5개의 단어만 단어 집합으로 저장

vocab_size = 5
vocab = vocab.most_common(vocab_size) # 등장 빈도수가 높은 상위 5개의 단어만 저장
print(vocab)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]


In [81]:
#앞서 Counter()를 사용했을 때와 결과 같음
# 이전 실습들과 마찬가지로 높은 빈도수를 가진 단어일수록 낮은 정수 인덱스를 부여

# 그런데 이번에는 enumerate()를 사용하여 좀 더 짧은 코드로 인덱스를 부여

word_to_index = {word[0] : index + 1 for index, word in enumerate(vocab)}
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [82]:
# 인덱스를 부여할 때는 enumerate()를 사용하는 것이 편리

---

In [85]:
# (+a) enumerate 이해하기

# enumerate()는 순서가 있는 자료형(list, set, tuple, dictionary, string)을 입력으로 받아 인덱스를 순차적으로 함께 리턴함

test_input = ['a', 'b', 'c', 'd', 'e']
for index, value in enumerate(test_input): # 입력의 순서대로 0부터 인덱스를 부여함.
    print("value : {}, index: {}".format(value, index))


value : a, index: 0
value : b, index: 1
value : c, index: 2
value : d, index: 3
value : e, index: 4


---

In [91]:
# 5) 케라스(Keras)의 텍스트 전처리
# 정수 인코딩을 위해서 케라스의 전처리 도구인 토크나이저를 사용

from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

# fit_on_texts()안에 코퍼스를 입력으로 하면 빈도수를 기준으로 단어 집합을 생성.
tokenizer.fit_on_texts(preprocessed_sentences)

# fit_on_texts는 입력한 텍스트로부터 단어 빈도수가 높은 순으로 낮은 정수 인덱스를 부여하는데,
# 정확히 앞서 설명한 정수 인코딩 작업이 이루어진다고 보면됨

# [ word_index ] : 인덱스 부여
# [ word_counts ] : 단어 카운팅
# [ texts_to_sequences() ] : 코퍼스의 단어를 인덱스로 변환
# tokenizer = Tokenizer(num_words=숫자) : 특정 상위 빈도수까지의 단어만 사용한다고 지정

In [93]:
# (1) 각 단어에 인덱스 부여 => [ word_index ]
# - 각 단어의 빈도수가 높은 순서대로 인덱스가 부여된 것을 확인
print(tokenizer.word_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}


In [89]:
# (2) 각 단어의 카운팅 => [ word_counts ]
print(tokenizer.word_counts)

OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])


In [129]:
# (3) 입력된 코퍼스를 단어 인덱스로 변환 => [ texts_to_sequences() ]
print(f'{tokenizer.word_index}\n')
for i in range(len(preprocessed_sentences)):
    print(f"{tokenizer.texts_to_sequences(preprocessed_sentences)[i]} : {preprocessed_sentences[i]}", sep='\n')

{'OOV': 1, 'barber': 2, 'secret': 3, 'huge': 4, 'kept': 5, 'person': 6, 'word': 7, 'keeping': 8, 'good': 9, 'knew': 10, 'driving': 11, 'crazy': 12, 'went': 13, 'mountain': 14}

[2, 6] : ['barber', 'person']
[2, 1, 6] : ['barber', 'good', 'person']
[2, 4, 6] : ['barber', 'huge', 'person']
[1, 3] : ['knew', 'secret']
[3, 5, 4, 3] : ['secret', 'kept', 'huge', 'secret']
[4, 3] : ['huge', 'secret']
[2, 5, 1] : ['barber', 'kept', 'word']
[2, 5, 1] : ['barber', 'kept', 'word']
[2, 5, 3] : ['barber', 'kept', 'secret']
[1, 1, 4, 3, 1, 2, 1] : ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy']
[2, 1, 4, 1] : ['barber', 'went', 'huge', 'mountain']


In [131]:
# (4) 빈도수가 높은 상위 몇 개의 단어만 사용하겠다고 지정 => tokenizer = Tokenizer(num_words=숫자)
vocab_size = 5
tokenizer = Tokenizer(num_words = vocab_size + 1) # 상위 5개 단어만 사용
tokenizer.fit_on_texts(preprocessed_sentences)

# num_words에서 +1을 더해서 값을 넣어주는 이유
# -> num_words는 숫자를 0부터 카운트하기 때문에.
# -> 만약 5를 넣으면 0 ~ 4번 단어 보존을 의미하게 되므로
# -> 뒤의 실습에서 1번 단어부터 4번 단어만 남게됨. 1 ~ 5번 단어까지 사용하고 싶다면 '+1'을 해줘야 하는 것임

# 실질적으로 숫자 0에 지정된 단어가 존재하지 않는데도 케라스 토크나이저가 숫자 0까지 단어 집합의 크기로 산정하는 이유
# -> 자연어 처리에서 패딩(padding)이라는 작업 때문
# -> 일단, 숫자 0도 단어 집합의 크기로 고려해야한다고만 이해

In [132]:
print(tokenizer.word_index)
print()
print(tokenizer.word_counts)
# 상위 5개의 단어만 사용하겠다고 선언하였는데 여전히 13개의 단어가 모두 출력

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}

OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])


In [133]:
# 사실 실제 적용은 texts_to_sequences를 사용할 때만 적용
print(tokenizer.texts_to_sequences(preprocessed_sentences))

# 코퍼스에 대해서 각 단어를 이미 정해진 인덱스로 변환하는데,
# 상위 5개의 단어만을 사용하겠다고 지정하였으므로 1번 단어부터 5번 단어까지만 보존되고 나머지 단어들은 제거됨

[[1, 5], [1, 5], [1, 3, 5], [2], [2, 4, 3, 2], [3, 2], [1, 4], [1, 4], [1, 4, 2], [3, 2, 1], [1, 3]]


In [134]:
# (+a) 경험상, 그다지 필요없다고 하긴함
# 만약 word_index와 word_counts에서도 지정된 num_words만큼의 단어만 남기고 싶다면 아래의 코드도 방법
# ----------------------------------------------------------------------------------------------------
# tokenizer = Tokenizer()
# tokenizer.fit_on_texts(preprocessed_sentences)

# vocab_size = 5
# words_frequency = [word for word, index in tokenizer.word_index.items() if index >= vocab_size + 1] 

# # 인덱스가 5 초과인 단어 제거
# for word in words_frequency:
#     del tokenizer.word_index[word] # 해당 단어에 대한 인덱스 정보를 삭제
#     del tokenizer.word_counts[word] # 해당 단어에 대한 카운트 정보를 삭제

# print(tokenizer.word_index)
# print(tokenizer.word_counts)
# print(tokenizer.texts_to_sequences(preprocessed_sentences))

In [135]:
# oov_token활용
# - 케라스 토크나이저는 기본적으로 단어 집합에 없는 단어인 OOV에 대해서는 단어를 정수로 바꾸는 과정에서 아예 단어를 제거한다는 특징이 있음
# - 단어 집합에 없는 단어들은 OOV로 간주하여 보존하고 싶다면 Tokenizer의 인자 oov_token을 사용

# 숫자 0과 OOV를 고려해서 단어 집합의 크기는 +2
vocab_size = 5
tokenizer = Tokenizer(num_words = vocab_size + 2, oov_token = 'OOV')
tokenizer.fit_on_texts(preprocessed_sentences)

# 만약 oov_token을 사용하기로 했다면 케라스 토크나이저는 기본적으로 'OOV'의 인덱스를 1로 합니다.
print('단어 OOV의 인덱스 : {}'.format(tokenizer.word_index['OOV']))

단어 OOV의 인덱스 : 1


In [136]:
# 코퍼스에 대해서 정수 인코딩을 진행
print(f'{tokenizer.word_index}\n')
for i in range(len(preprocessed_sentences)):
    print(f"{tokenizer.texts_to_sequences(preprocessed_sentences)[i]} : {preprocessed_sentences[i]}", sep='\n')

{'OOV': 1, 'barber': 2, 'secret': 3, 'huge': 4, 'kept': 5, 'person': 6, 'word': 7, 'keeping': 8, 'good': 9, 'knew': 10, 'driving': 11, 'crazy': 12, 'went': 13, 'mountain': 14}

[2, 6] : ['barber', 'person']
[2, 1, 6] : ['barber', 'good', 'person']
[2, 4, 6] : ['barber', 'huge', 'person']
[1, 3] : ['knew', 'secret']
[3, 5, 4, 3] : ['secret', 'kept', 'huge', 'secret']
[4, 3] : ['huge', 'secret']
[2, 5, 1] : ['barber', 'kept', 'word']
[2, 5, 1] : ['barber', 'kept', 'word']
[2, 5, 3] : ['barber', 'kept', 'secret']
[1, 1, 4, 3, 1, 2, 1] : ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy']
[2, 1, 4, 1] : ['barber', 'went', 'huge', 'mountain']


In [137]:
# 빈도수 상위 5개의 단어는 2 ~ 6까지의 인덱스를 가졌으며,
# 그 외 단어 집합에 없는 'good'과 같은 단어들은 전부 'OOV'의 인덱스인 1로 인코딩

---

In [58]:
# 수정해서 필요한 부분까지만 사용
# - 활용o : 불용어 제거, 단어 길이 2이하 제거
# - 활용x : 빈도수 표시하는 것은 자동화해서 만들어주는 모듈로

vocab = {}
preprocessed_sentences = []
stop_words = set(stopwords.words('english'))

for sentence in sentences:
    # 단어 토큰화
    tokenized_sentence = word_tokenize(sentence)
    result = []

    for word in tokenized_sentence: 
        word = word.lower() # 모든 단어를 소문자화하여 단어의 개수를 줄인다.
        if word not in stop_words: # 단어 토큰화 된 결과에 대해서 불용어를 제거한다.
            if len(word) > 2: # 단어 길이가 2이하인 경우에 대하여 추가로 단어를 제거한다.
                result.append(word)
                if word not in vocab:
                    vocab[word] = 0 
                vocab[word] += 1
    preprocessed_sentences.append(result) 
print(preprocessed_sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


---

## 5) 패딩(Padding)

In [ ]:
# 자연어 처리를 하다보면, 각 문장(or 문서)은 서로 길이가 다를 수 있음
# but, 기계는 길이가 전부 동일한 문서들에 대해서는 하나의 행렬로 보고,
# 한꺼번에 묶어서 처리할 수 있으니 병렬 연산을 위해서!!!
# => 여러 문장의 길이를 임의로 동일하게 맞춰주는 작업이 필요

#### (1) Numpy로 패딩하기

In [142]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

# 텍스트
preprocessed_sentences

# 단어 집합을 만들고, 정수 인코딩을 수행
tokenizer = Tokenizer()
tokenizer.fit_on_texts(preprocessed_sentences)
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [144]:
# 모두 동일한 길이로 맞춰주기 위해서,
# 이 중에서 가장 길이가 긴 문장의 길이를 계산

max_len = max(len(item) for item in encoded)
print('최대 길이 :',max_len)


최대 길이 : 7


In [145]:
# 가장 길이가 긴 문장의 길이는 7
# -> 모든 문장의 길이를 7로 맞춰주겠음

# 이때 가상의 단어 'PAD'를 사용.
# 'PAD'라는 단어가 있다고 가정, 이 단어는 0번 단어라고 정의
# 길이가 7보다 짧은 문장에는 숫자 0을 채워서 길이 7로 맞춰줌

for sentence in encoded:
    while len(sentence) < max_len:
        sentence.append(0)

padded_np = np.array(encoded)
padded_np

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

In [146]:
# 이들을 하나의 행렬로 보고, 병렬 처리를 할 수 있음.
# 또한, 0번 단어는 사실 아무런 의미도 없는 단어이기 때문에
# 자연어 처리하는 과정에서 기계는 0번 단어를 무시하게 될 것임

In [ ]:
# 패딩(padding) : 데이터에 특정 값을 채워서 데이터의 크기(shape)를 조정하는 것
# - 제로 패딩(zero padding) : 숫자 0을 사용하면

#### (2) 케라스 전처리 도구로 패딩하기

In [156]:
# pad_sequences() : 케라스에서는 제공하는 패딩 기능
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [157]:
# encoded 값이 위에서 이미 패딩 후의 결과로 저장되었기 때문에
# 패딩 이전의 값으로 다시 되돌리자

encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [158]:
# 케라스로 패딩 수행 (앞0)
padded = pad_sequences(encoded)
padded

array([[ 0,  0,  0,  0,  0,  1,  5],
       [ 0,  0,  0,  0,  1,  8,  5],
       [ 0,  0,  0,  0,  1,  3,  5],
       [ 0,  0,  0,  0,  0,  9,  2],
       [ 0,  0,  0,  2,  4,  3,  2],
       [ 0,  0,  0,  0,  0,  3,  2],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  2],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 0,  0,  0,  1, 12,  3, 13]])

In [150]:
# Numpy로 패딩을 진행하였을 때와는 패딩 결과가 다름
# -> pad_sequences는 기본적으로 문서의 뒤에 0을 채우는 것이 아니라
# -> 앞에 0으로 채우기 때문.

# 뒤에 0을 채우고 싶다면, 인자로 padding='post'를 주면됨
padded = pad_sequences(encoded, padding='post')
padded

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

In [151]:
# Numpy를 이용하여 패딩을 했을 때와 결과가 동일.
# 제로 결과가 동일한지 두 결과를 비교.
(padded == padded_np).all()

True

In [152]:
# 가장 긴 길이를 가진 문서의 길이를 기준으로 패딩을 한다고 가정하였지만,
# 실제로는 꼭 가장 긴 문서의 길이를 기준으로 해야하는 것은 아님.

# 길이에 제한을 두고 패딩할 수 있음.
# [ maxlen ] 인자로 정수를 주면,
# 해당 정수로 모든 문서의 길이를 동일하게 함.

padded = pad_sequences(encoded, padding='post', maxlen=5)
padded

array([[ 1,  5,  0,  0,  0],
       [ 1,  8,  5,  0,  0],
       [ 1,  3,  5,  0,  0],
       [ 9,  2,  0,  0,  0],
       [ 2,  4,  3,  2,  0],
       [ 3,  2,  0,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  2,  0,  0],
       [ 3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0]])

In [ ]:
# 길이가 5보다 짧은 문서들은 0으로 패딩되고,
# 기존에 5보다 길었다면 데이터가 손실

# ex) [ 7,  7,  3,  2, 10,  1, 11] -> [ 3,  2, 10,  1, 11]

In [153]:
# 데이터가 손실될 경우에 앞의 단어가 아니라 뒤의 단어가 삭제되도록 하고싶다면,
# truncating이라는 인자를 사용.
# truncating='post'를 사용할 경우 뒤의 단어가 삭제.

padded = pad_sequences(encoded, padding='post', truncating='post', maxlen=5)
padded

# ex) [ 7,  7,  3,  2, 10,  1, 11] -> [ 7,  7,  3,  2, 10]

array([[ 1,  5,  0,  0,  0],
       [ 1,  8,  5,  0,  0],
       [ 1,  3,  5,  0,  0],
       [ 9,  2,  0,  0,  0],
       [ 2,  4,  3,  2,  0],
       [ 3,  2,  0,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  2,  0,  0],
       [ 7,  7,  3,  2, 10],
       [ 1, 12,  3, 13,  0]])

In [154]:
# 숫자 0으로 패딩하는 것은 널리 퍼진 관례이긴 하지만,
# 반드시 지켜야하는 규칙은 아님.

# 만약, 숫자 0이 아니라 다른 숫자를 패딩을 위한 숫자로 사용하고 싶다면
# 이 또한 가능합니다. 현재 사용된 정수들과 겹치지 않도록,
# 단어 집합의 크기에 +1을 한 숫자로 사용

last_value = len(tokenizer.word_index) + 1 # 단어 집합의 크기보다 1 큰 숫자를 사용
print(last_value)

14


In [155]:
# 현재 단어가 총 13개이고, 1번부터 13번까지 정수가 사용되었으므로
# 단어 집합의 크기에 +1을 하면 마지막 숫자인 13보다 1이 큰 14를 얻습니다.
# pad_sequences의 인자로 value를 사용하면 0이 아닌 다른 숫자로 패딩이 가능

padded = pad_sequences(encoded, padding='post', value=last_value)
padded

array([[ 1,  5, 14, 14, 14, 14, 14],
       [ 1,  8,  5, 14, 14, 14, 14],
       [ 1,  3,  5, 14, 14, 14, 14],
       [ 9,  2, 14, 14, 14, 14, 14],
       [ 2,  4,  3,  2, 14, 14, 14],
       [ 3,  2, 14, 14, 14, 14, 14],
       [ 1,  4,  6, 14, 14, 14, 14],
       [ 1,  4,  6, 14, 14, 14, 14],
       [ 1,  4,  2, 14, 14, 14, 14],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13, 14, 14, 14]])

---

## 6) 원-핫 인코딩(One-Hot Encoding)

### 6-1) 원-핫 인코딩이란

In [ ]:
# 원-핫 인코딩에 대해서 배우기에 앞서 단어 집합(vocabulary) 에 대해서 정의해보자
# - 단어 집합 : 텍스트의 모든 단어를 중복을 허용하지 않고 모은 것(서로 다른 단어들의 집합)
# 원-핫 인코딩을 위해서 먼저 해야할 일은 단어 집합을 만드는 일

In [159]:
# 각 단어에 고유한 정수 인덱스를 부여하였다고 합시다. 이제 이 숫자로 바뀐 단어들을 벡터로 다루고 싶다면?

# 원-핫 인코딩(One-Hot Encoding) : 단어 집합의 크기를 벡터의 차원으로 하고,
#                                 표현하고 싶은 단어의 인덱스에 1의 값을 부여하고,
#                                 다른 인덱스에는 0을 부여하는 단어의 벡터 표현 방식

# - 문자를 숫자로 바꾸는 여러가지 기법 중에서 단어를 표현하는 가장 기본적인 표현 방법
# - 머신 러닝, 딥 러닝을 하기 위해서는 반드시 배워야 하는 표현 방법

# 원-핫 벡터(One-Hot vector) : 원-핫 인코딩으로 표현된 벡터

### 6-2) 원-핫 인코딩(One-Hot Encoding) _ 파이썬

In [ ]:
# < 원-핫 인코딩을 두 가지 과정 >
# 첫째, 정수 인코딩을 수행 => 각 단어에 고유한 정수를 부여
# 둘째, 표현하고 싶은 단어의 고유한 정수를 인덱스로 간주하고,
# - 해당 위치에 1을 부여하고, 다른 단어의 인덱스의 위치에는 0을 부여

In [160]:
# (1) 토큰화 수행 (feat. Okt 형태소 분석기)
from konlpy.tag import Okt  

okt = Okt()  
tokens = okt.morphs("나는 자연어 처리를 배운다")  
print(tokens)

['나', '는', '자연어', '처리', '를', '배운다']


In [163]:
# (2) 각 토큰에 대해서 고유한 정수 부여
# - 빈도수 순으로 단어를 정렬하여 정수를 부여하는 경우가 많음 (지금은 문장이 짧아서 빈도 고려x)

word_to_index = {word : index for index, word in enumerate(tokens)}
print('단어 집합 :',word_to_index)

단어 집합 : {'나': 0, '는': 1, '자연어': 2, '처리': 3, '를': 4, '배운다': 5}


In [165]:
# 토큰을 입력하면 해당 토큰에 대한 원-핫 벡터를 만들어내는 함수
def one_hot_encoding(word, word_to_index):
    one_hot_vector = [0]*(len(word_to_index))
    index = word_to_index[word]
    one_hot_vector[index] = 1
    return one_hot_vector

one_hot_encoding("자연어", word_to_index)
# '자연어'는 정수 2이므로 원-핫 벡터는 인덱스 2의 값이 1이며, 나머지 값은 0인 벡터가 나옴

[0, 0, 1, 0, 0, 0]

### 6-3) 원-핫 인코딩(One-Hot Encoding) _ 케라스(Keras) 이용

In [166]:
# 케라스는 원-핫 인코딩을 수행하는 유용한 도구 to_categorical()를 지원
# -> 케라스만으로 정수 인코딩과 원-핫 인코딩을 순차적으로 진행
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

# 케라스 토크나이저를 이용한 정수 인코딩
text = "나랑 점심 먹으러 갈래 점심 메뉴는 햄버거 갈래 갈래 햄버거 최고야"

tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
print('단어 집합 :',tokenizer.word_index)

단어 집합 : {'갈래': 1, '점심': 2, '햄버거': 3, '나랑': 4, '먹으러': 5, '메뉴는': 6, '최고야': 7}


In [167]:
# 생성된 단어 집합(vocabulary)에 있는 단어들로만 구성된 텍스트가 있다면,
# [ texts_to_sequences() ]를 통해서 이를 정수 시퀀스로 변환가능

# -> 생성된 단어 집합 내의 일부 단어들로만 구성된 서브 텍스트인 sub_text를 만들어 확인
sub_text = "점심 먹으러 갈래 메뉴는 햄버거 최고야"
encoded = tokenizer.texts_to_sequences([sub_text])[0]
print(encoded)

[2, 5, 1, 6, 3, 7]


In [168]:
# 해당 결과를 가지고, 원-핫 인코딩을 진행
# 케라스는 정수 인코딩 된 결과로부터 원-핫 인코딩을 수행하는 [ to_categorical() ]를 지원

one_hot = to_categorical(encoded)
print(one_hot)

[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
# "점심 먹으러 갈래 메뉴는 햄버거 최고야"라는 문장이 [2, 5, 1, 6, 3, 7]로 '정수 인코딩'이 되고나서,
# 각각의 인코딩 된 결과를 인덱스로 '원-핫 인코딩'이 수행된 모습

### 6-3) 원-핫 인코딩(One-Hot Encoding)의 한계

In [ ]:
# 단점
# (1) 벡터의 차원이 늘어남
# - 단어의 개수가 늘어날수록, 벡터를 저장하기 위해 필요한 공간이 계속 늘어남
# - 원 핫 벡터는 단어 집합의 크기가 곧 벡터의 차원 수가 됨
# - 1000개의 코퍼스가 있는 경우, 각 1개의 코퍼스는 1(1개), 0(999개)를 갖게 됨 => 저장 공간 측면에서 비효율적

# (2) 단어의 유사도를 표현하지 못함 => 검색 시스템 등에서는 문제가 될 소지가 있음
# 예를 들어서 늑대, 호랑이, 강아지, 고양이라는 4개의 단어에 대해서
# 원-핫 인코딩을 해서 각각, [1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]
# -> 강아지와 늑대가 유사하고, 호랑이와 고양이가 유사하다는 것을 표현할 수가 없음

# '종로 숙소' 로 검색했을 경우, [ '종로 게하', '종로 호텔' ]등은 볼 수 없다는 말
# - 연관검색어를 볼 수 없음

In [ ]:
# 이러한 단점( (1), (2) )을 해결하기 위해 단어의 잠재 의미를 반영하여
# 다차원 공간에 벡터화 하는 기법으로 크게 두 가지가 있습니다.

# 첫째는 카운트 기반의 벡터화 방법인 LSA(잠재 의미 분석), HAL 등이 있음
# 둘째는 예측 기반으로 벡터화하는 NNLM, RNNLM, Word2Vec, FastText 등이 있음
# + 카운트 기반과 예측 기반 두 가지 방법을 모두 사용하는 방법으로 GloVe라는 방법이 있음

# => 대부분은 워드 임베딩 챕터에서 다루게 됩니다.

---

## 7) 데이터의 분리(Splitting Data)

In [169]:
# 지도 학습을 위한 데이터 분리 작업
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

### (1) 지도 학습(Supervised Learning)

In [175]:
# 예측한 답과 실제 정답인 y_test를 비교하면서
# 기계가 정답을 얼마나 맞췄는지를 평가함
# => 이 수치가 기계의 [ 정확도(Accuracy) ]

### (2) X와 y분리하기

In [171]:
# 2-1) [ zip 함수 ]
# zip()함수 : '동일한 개수'를 가지는 시퀀스 자료형에서 각 순서에 등장하는 원소들끼리 묶어주는 역할
# -리스트의 리스트 구성에서 zip 함수는 X와 y를 분리하는데 유용

X, y = zip(['a', 1], ['b', 2], ['c', 3])
print('X 데이터 :',X)
print('y 데이터 :',y)

X 데이터 : ('a', 'b', 'c')
y 데이터 : (1, 2, 3)


In [174]:
# 리스트의 리스트 또는 행렬 또는 뒤에서 배울 개념인 2D 텐서.
sequences = [['a', 1], ['b', 2], ['c', 3]]
X, y = zip(*sequences)
print('X 데이터 :',X)
print('y 데이터 :',y)

X 데이터 : ('a', 'b', 'c')
y 데이터 : (1, 2, 3)


In [176]:
# 2-2) [ 데이터프레임 ]

values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']

df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [178]:
X = df['메일 본문']
y = df['스팸 메일 유무']

print('X 데이터 :',X.to_list())
print('y 데이터 :',y.to_list())

X 데이터 : ['당신에게 드리는 마지막 혜택!', '내일 뵐 수 있을지 확인 부탁드...', '도연씨. 잘 지내시죠? 오랜만입...', '(광고) AI로 주가를 예측할 수 있다!']
y 데이터 : [1, 0, 0, 1]


In [179]:
# 2-3) [ Numpy ]
# 임의의 데이터를 만들어서 Numpy의 슬라이싱(slicing)을 사용하여 데이터를 분리

np_array = np.arange(0,16).reshape((4,4))
print('전체 데이터 :')
print(np_array)

전체 데이터 :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [180]:
# 마지막 열을 제외하고 X데이터에 저장합니다. 마지막 열만을 y데이터에 저장
X = np_array[:, :3]
y = np_array[:,3]

print('X 데이터 :')
print(X)
print('y 데이터 :',y)

X 데이터 :
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
y 데이터 : [ 3  7 11 15]


### (3) 테스트 데이터 분리하기

In [181]:
# 3-1) [ train_test_split() ] => 사이킷 런을 이용
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=1234)

# X : 독립 변수 데이터. (배열이나 데이터프레임)
# y : 종속 변수 데이터. 레이블 데이터.
# test_size : 테스트용 데이터 개수를 지정한다. 1보다 작은 실수를 기재할 경우, 비율을 나타낸다.
# train_size : 학습용 데이터의 개수를 지정한다. 1보다 작은 실수를 기재할 경우, 비율을 나타낸다.
# random_state : 난수 시드
# -> train_size와 test_size는 둘 중 하나만 기재해도 됨

# 임의로 X와 y 데이터를 생성
X, y = np.arange(10).reshape((5, 2)), range(5)

print('X 전체 데이터 :')
print(X)
print('y 전체 데이터 :')
print(list(y))

X 전체 데이터 :
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
y 전체 데이터 :
[0, 1, 2, 3, 4]


In [183]:
# train_test_split()은 기본적으로 데이터의 순서를 섞고나서 훈련 데이터와 테스트 데이터를 분리

# - random_state의 값을 특정 숫자로 기재해준 뒤에 다음에도 동일한 숫자로 기재해주면,
# - 항상 동일한 훈련 데이터와 테스트 데이터를 얻을 수 있음
# -값을 변경하면 다른 순서로 섞인 채 분리되므로 이전과 다른 훈련 데이터와 테스트 데이터를 얻음

# 7:3의 비율로 훈련 데이터와 테스트 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234)
print('X 훈련 데이터 :')
print(X_train)
print('X 테스트 데이터 :')
print(X_test)

X 훈련 데이터 :
[[2 3]
 [4 5]
 [6 7]]
X 테스트 데이터 :
[[8 9]
 [0 1]]


In [184]:
print('y 훈련 데이터 :')
print(y_train)
print('y 테스트 데이터 :')
print(y_test)

y 훈련 데이터 :
[1, 2, 3]
y 테스트 데이터 :
[4, 0]


In [185]:
# random_state의 값을 변경
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

print('y 훈련 데이터 :')
print(y_train)
print('y 테스트 데이터 :')
print(y_test)

y 훈련 데이터 :
[4, 0, 3]
y 테스트 데이터 :
[2, 1]


In [186]:
# random_state 값이 1234일 때와 전혀 다른 y데이터가 출력
# -> 데이터가 다른 순서로 섞였다는 의미

# random_state의 값을 고정해두면 실행할 때마다 항상 동일한 순서로 데이터를 섞으므로,
# 동일한 코드를 다음에 재현하고자 할 때 사용

In [189]:
# 3-2) 수동으로 분리하기
# train_test_split()과 다른 점은 데이터가 섞이지 않은 채 어느 지점에서 데이터를 앞과 뒤로 분리했다는 점입니다.
# 만약, 수동으로 분리하게 된다면 데이터를 분리하기 전에 수동으로 데이터를 섞는 과정이 필요할 수 있습

---

### 8) 한국어 전처리 패키지
---
https://wikidocs.net/92961